name: ci-pipeline

on: [push]

jobs:
  run:

    name: Run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'

      - name: Get Composer cache directory
        id: composer-cache
        working-directory: ./app
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        working-directory: ./app
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run CI
        working-directory: ./app
        run: composer run-script ci
